


CREATE table BANK(
CODE char(3) PRIMARY KEY, 
NAME varchar (20), 
ADDR varchar (50)
);



CREATE table BANK_BRANCH (
BCODE char(3), 
BRANCHNO int PRIMARY KEY, 
ADDR varchar (50),
FOREIGN KEY(BCODE) REFERENCES BANK(CODE)
);


CREATE table ACCOUNT (
ACCTNO int primary key, 
BALANCE int, 
TYPE varchar(20), 
BCODE char(3), 
BNO int,
FOREIGN KEY (BNO) REFERENCES BANK_BRANCH(BRANCHNO),
FOREIGN KEY (BCODE) REFERENCES BANK(CODE) );




CREATE table CUSTOMER (
SSN char(09) PRIMARY KEY, 
NAME varchar (30), 
PHONE int, 
ADDR varchar (50) );



CREATE table LOAN (
LOANNO int PRIMARY KEY, 
AMOUNT int, 
TYPE varchar (20), 
BCODE char(3), 
BNO int,
FOREIGN KEY (BCODE) REFERENCES BANK(CODE),
FOREIGN KEY (BNO) REFERENCES BANK_BRANCH(BRANCHNO)
);

CREATE TABLE ACCOUNT_CUSTOMER (
SSN CHAR(9) PRIMARY KEY,
ACCTNO INT NOT NULL,
FOREIGN KEY (ACCTNO) REFERENCES ACCOUNT(ACCTNO) );

CREATE TABLE LOAN_CUSTOMER (
SSN CHAR(9) PRIMARY KEY,
LOANNO INT NOT NULL,
FOREIGN KEY (LOANNO) REFERENCES LOAN(LOANNO) );







